# General settings
seed: 42
device: 'cuda'  # 'cuda' or 'cpu'

# Data settings
data:
  features_dir: '/mnt/shareEEx/liuyang/code/SE_IMR_MTL_KD/pretrain_model/wav2vec2-base-100h'
  labels_file: '/mnt/shareEEx/liuyang/code/SE_IMR_MTL_KD/data/organized_datasets/v1.6/labels_concensus.csv'
  batch_size: 32
  num_workers: 4
  pin_memory: true

# Model settings
model:
  input_size: 768  # wav2vec2 feature dimension
  hidden_size: 256
  num_layers: 2
  output_size: 3  # V, A, D regression outputs
  dropout: 0.2

# Training settings
training:
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler:
    factor: 0.5
    patience: 3
    min_lr: 0.00001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Output settings
output:
  save_dir: 'results/vad_regression'
  log_interval: 10  # Print metrics every N batches
  save_interval: 5  # Save model every N epochs